// Compiles the message catalogs in i18n/ into common/i18n.generated.ts — the
// ONE module both the server and the bundled client import (like common/version.ts,
// it's gitignored and generated; `deno task i18n` runs first in build/dev/test
// and in CI before the type check). It:
//   - pre-parses every ICU message to an I18nNode[] AST (so no parser ships), and
//   - derives `MessageKey` + a per-key params type map FROM en.json,
// so a missing key or wrong argument at a `t(...)` call site is a compile error.
// en.json is the source of truth: it defines the key set and the param types;
// every other i18n/<locale>.json is a machine-written translation of it.

import { collectParams, parseMessage } from "./i18nParse.ts";
import type { I18nNode } from "../common/i18n.ts";

type Entry = { message: string };
type Catalog = Record<string, Entry>;

const I18N_DIR = new URL("../i18n/", import.meta.url);
const OUT = new URL("../common/i18n.generated.ts", import.meta.url);

// Locale catalogs are `<code>.json`; the non-catalog files (glossary.json,
// config.json) are excluded so they don't become bogus locales.
const NON_CATALOG = new Set(["glossary.json", "config.json"]);
const localeFiles: string[] = [];
for await (const e of Deno.readDir(I18N_DIR)) {
  if (e.isFile && e.name.endsWith(".json") && !NON_CATALOG.has(e.name)) {
    localeFiles.push(e.name.slice(0, -".json".length));
  }
}
// `en` first (the guaranteed fallback), then the rest alphabetically.
localeFiles.sort((a, b) => (a === "en" ? -1 : b === "en" ? 1 : a < b ? -1 : 1));
if (localeFiles[0] !== "en") throw new Error("i18n/en.json is required");

const read = async (locale: string): Promise<Catalog> =>
  JSON.parse(await Deno.readTextFile(new URL(`${locale}.json`, I18N_DIR)));

const en = await read("en");
const keys = Object.keys(en).sort();

// Compile each locale's messages to ASTs, keyed by the en.json key set. A locale
// missing a key just omits it — the runtime falls back to the English AST (the
// i18n:check gate, later, makes missing keys a hard failure).
const catalog: Record<string, Record<string, I18nNode[]>> = {};
for (const locale of localeFiles) {
  const src = locale === "en" ? en : await read(locale);
  const compiled: Record<string, I18nNode[]> = {};
  for (const key of keys) {
    const entry = src[key];
    if (entry) compiled[key] = parseMessage(entry.message);
  }
  catalog[locale] = compiled;
}

// Per-key params type, derived from the English message.
const paramsType = (key: string): string => {
  const params = collectParams(catalog.en[key]);
  const names = Object.keys(params).sort();
  if (names.length === 0) return "Record<string, never>";
  return `{ ${
    names.map((n) => `${JSON.stringify(n)}: ${params[n]}`).join("; ")
  } }`;
};

const body =
  `// GENERATED by scripts/genI18n.ts from i18n/*.json — do not edit or commit.
import type { I18nNode } from "./i18n.ts";

export const locales = [${
    localeFiles.map((l) => JSON.stringify(l)).join(", ")
  }] as const;
export type Locale = (typeof locales)[number];

export type MessageKey =
${keys.map((k) => `  | ${JSON.stringify(k)}`).join("\n")};

export type MessageParams = {
${keys.map((k) => `  ${JSON.stringify(k)}: ${paramsType(k)};`).join("\n")}
};

export const catalog: Record<Locale, Record<string, I18nNode[]>> = ${
    JSON.stringify(catalog, null, 2)
  };
`;

await Deno.writeTextFile(OUT, body);
console.log(
  `i18n: ${keys.length} keys × ${localeFiles.length} locale(s) → common/i18n.generated.ts`,
);
