// Compiles each message catalog in i18n/ (see CATALOGS in i18nLib.ts) into its
// generated module — the app's into common/i18n.generated.ts, the ONE module both
// the server and the bundled client import; the privacy page's into a
// server-only one. Like common/version.ts they're gitignored and generated
// (`deno task i18n` runs first in build/dev/test and in CI before the type
// check). For each catalog it:
//   - pre-parses every ICU message to an I18nNode[] AST (so no parser ships), and
//   - derives `MessageKey` + a per-key params type map FROM its en.json,
// so a missing key or wrong argument at a call site is a compile error.
// en.json is the source of truth: it defines the key set and the param types;
// every other <locale>.json beside it is a machine-written translation of it.

import { dirname, relative } from "@std/path/posix";
import { collectParams, parseMessage } from "./i18nParse.ts";
import { CATALOGS, type CatalogSpec } from "./i18nLib.ts";
import type { I18nNode } from "../common/i18n.ts";

type Entry = { message: string };
type Catalog = Record<string, Entry>;

const ROOT = new URL("../", import.meta.url);

// Locale catalogs are `<code>.json`; the non-catalog files (glossary.json,
// config.json) are excluded so they don't become bogus locales, and the
// sub-catalog directories are skipped by the isFile check.
const NON_CATALOG = new Set(["glossary.json", "config.json"]);

const compile = async ({ dir, out }: CatalogSpec) => {
  const catalogDir = new URL(`i18n/${dir}`, ROOT);
  const localeFiles: string[] = [];
  for await (const e of Deno.readDir(catalogDir)) {
    if (e.isFile && e.name.endsWith(".json") && !NON_CATALOG.has(e.name)) {
      localeFiles.push(e.name.slice(0, -".json".length));
    }
  }
  // `en` first (the guaranteed fallback), then the rest alphabetically.
  localeFiles.sort((a, b) => a === "en" ? -1 : b === "en" ? 1 : a < b ? -1 : 1);
  if (localeFiles[0] !== "en") {
    throw new Error(`i18n/${dir}en.json is required`);
  }

  const read = async (locale: string): Promise<Catalog> =>
    JSON.parse(await Deno.readTextFile(new URL(`${locale}.json`, catalogDir)));

  const en = await read("en");
  const keys = Object.keys(en).sort();

  // Compile each locale's messages to ASTs, keyed by the en.json key set. A
  // locale missing a key just omits it — the runtime falls back to the English
  // AST (the i18n:check gate, later, makes missing keys a hard failure).
  const catalog: Record<string, Record<string, I18nNode[]>> = {};
  for (const locale of localeFiles) {
    const src = locale === "en" ? en : await read(locale);
    const compiled: Record<string, I18nNode[]> = {};
    for (const key of keys) {
      const entry = src[key];
      if (entry) compiled[key] = parseMessage(entry.message);
    }
    catalog[locale] = compiled;
  }

  // Per-key params type, derived from the English message.
  const paramsType = (key: string): string => {
    const params = collectParams(catalog.en[key]);
    const names = Object.keys(params).sort();
    // `Record<never, never>` (keyof → never) lets `t(key)` omit the params arg
    // for no-argument messages; keys with args keep their required params
    // object.
    if (names.length === 0) return "Record<never, never>";
    return `{ ${
      names.map((n) => `${JSON.stringify(n)}: ${params[n]}`).join("; ")
    } }`;
  };

  // The runtime's node type, imported relative to wherever this module lands.
  let runtime = relative(dirname(out), "common/i18n.ts");
  if (!runtime.startsWith(".")) runtime = `./${runtime}`;

  const body =
    `// GENERATED by scripts/genI18n.ts from i18n/${dir}*.json — do not edit or commit.
import type { I18nNode } from ${JSON.stringify(runtime)};

export const locales = [${
      localeFiles.map((l) => JSON.stringify(l)).join(", ")
    }] as const;
export type Locale = (typeof locales)[number];

export type MessageKey =
${keys.map((k) => `  | ${JSON.stringify(k)}`).join("\n")};

export type MessageParams = {
${keys.map((k) => `  ${JSON.stringify(k)}: ${paramsType(k)};`).join("\n")}
};

export const catalog: Record<Locale, Record<string, I18nNode[]>> = ${
      JSON.stringify(catalog, null, 2)
    };
`;

  await Deno.writeTextFile(new URL(out, ROOT), body);
  console.log(
    `i18n: ${keys.length} keys × ${localeFiles.length} locale(s) → ${out}`,
  );
};

for (const spec of CATALOGS) await compile(spec);
