// Bakes the build's git SHA into common/version.ts, the ONE source both sides
// read: the server imports it (beginLogger/endLogger) to stamp its own build,
// and the client bundles it to know which build it is. Run as part of
// `deno task build` / `deno task dev`; the file is gitignored — generated, never
// committed. Living in common/ (a pure leaf, imported by both server and client)
// means there is a single SHA string, so the server's build and the client
// bundle's baked value are byte-identical by construction — no env plumbing and
// no short-vs-full mismatch to make every client look perpetually stale.
//
// Uses the deploy-stamped GIT_SHA env if set (a build env that has it but no
// git), else the working tree's short SHA (local build / CI), else "dev" (an
// unbuilt checkout), in which case the version machinery no-ops (see
// noteServerVersion). Because it's a build artifact like public/js, `deno task
// start` requires a prior build — the same build-before-serve contract that
// already produces the client bundle.
const gitSha = async (): Promise<string> => {
  const fromEnv = Deno.env.get("GIT_SHA");
  if (fromEnv) return fromEnv;
  try {
    const out = await new Deno.Command("git", {
      args: ["rev-parse", "--short", "HEAD"],
    }).output();
    if (out.success) return new TextDecoder().decode(out.stdout).trim();
  } catch { /* git unavailable */ }
  return "dev";
};

const sha = await gitSha();
await Deno.writeTextFile(
  new URL("../common/version.ts", import.meta.url),
  `// GENERATED by scripts/genVersion.ts at build time — do not edit or commit.\n` +
    // `: string` widens the type off the baked literal — otherwise `deno check`
    // narrows SHA to e.g. "8e7f80d" and flags the `=== "dev"` guards (which read
    // "dev" on an unbuilt checkout) as impossible comparisons.
    `export const SHA: string = ${JSON.stringify(sha)};\n`,
);
console.log(`build version: ${sha}`);
