import { getDailyIteration } from "../db/iteration.ts";
import { newIteration } from "./newIteration.ts";

const ONE_MINUTE = 1_000 * 60;
const ONE_DAY = ONE_MINUTE * 60 * 24;

const ensureIteration = async (unix: number) => {
  const date = new Date(unix);
  const iteration = await getDailyIteration(
    date.getFullYear(),
    date.getMonth() + 1,
    date.getDate(),
  );
  if (!iteration) await newIteration(date);
};

const ensureIterations = async (offsetDays: number) => {
  let day = Date.now() - offsetDays * ONE_DAY;
  while (day < Date.now() + ONE_DAY) {
    await ensureIteration(day);
    day += ONE_DAY;
  }
};

// Daily iterations are generated by a single scheduled job.
//
// `ensureIteration` is check-then-create and not atomic, so if it runs
// concurrently on more than one isolate, two isolates can both observe "no
// iteration yet" for a new day and both create one — producing duplicate
// iterations for the same day. That is why generation must have a single
// writer.
//
// `Deno.cron` on Deno Deploy is a platform-scheduled job: it fires once per
// tick (not once per isolate) and never overlaps itself, so it is that single
// writer — and it runs on schedule regardless of traffic, unlike the old
// per-isolate cold-start backfill (which is what caused the race).
//
// It runs every minute over a 14-day window so, besides keeping today/tomorrow
// generated, it also:
//   - seeds a brand-new environment with recent history on its first tick, and
//   - backfills any days missed while the job wasn't running (up to 14 days).
// These are the jobs the removed cold-start backfill used to do, now handled by
// the single writer. It's idempotent: existing days are only read, never
// recreated. Registered at module top level (before `Deno.serve`) as required.
Deno.cron("ensure-iterations", "* * * * *", () => ensureIterations(14));
