import { getDailyIteration } from "../db/iteration.ts";
import { newIteration } from "./newIteration.ts";

const ONE_MINUTE = 1_000 * 60;
const ONE_DAY = ONE_MINUTE * 60 * 24;

const ensureIteration = async (unix: number) => {
  const date = new Date(unix);
  const iteration = await getDailyIteration(
    date.getFullYear(),
    date.getMonth() + 1,
    date.getDate(),
  );
  if (!iteration) await newIteration(date);
};

const ensureIterations = async (offsetDays: number) => {
  let day = Date.now() - offsetDays * ONE_DAY;
  while (day < Date.now() + ONE_DAY) {
    await ensureIteration(day);
    day += ONE_DAY;
  }
};

// Daily iterations are generated by a single scheduled job.
//
// `ensureIteration` is check-then-create and not atomic, so if it runs
// concurrently on more than one isolate, two isolates can both observe "no
// iteration yet" for a new day and both create one — producing duplicate
// iterations for the same day. That is why generation must have a single
// writer.
//
// `Deno.cron` on Deno Deploy is a platform-scheduled job: it fires once per
// tick (not once per isolate) and never overlaps itself, so it is that single
// writer. We therefore rely on it exclusively and do NOT also backfill on
// cold start (which ran on every ephemeral isolate and caused the race).
// Registered at module top level (before `Deno.serve`) as required.
Deno.cron("ensure-iterations", "* * * * *", () => ensureIterations(1));
