name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Install
        uses: denoland/setup-deno@v1

      - name: Build
        run: ./bundle

      - name: Extract branch
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Extract enviornment
        shell: bash
        run: echo "##[set-output name=env;]$([ ${{ steps.extract_branch.outputs.branch }} = prod ] && echo prod || echo dev)"
        id: extract_env
      
      - name: Deploy
        uses: denoland/deployctl@v1
        with:
          project: "blocktol-${{ steps.extract_env.outputs.env }}"
          entrypoint: "./server/index.ts"