name: Deploy

on: 
  workflow_dispatch:
    inputs:
      tag:
        required: true
      env:
        required: true
        default: 'dev'
        options:
          - dev
          - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build & commit
    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@v2
      - run: rm public/js/.gitignore
      - run: ./bundle
      - run: git add --all
      - run: git config --global user.email "deploy+${{ github.actor }}@blocktol.com"
      - run: git config --global user.name "${{ github.actor }}"
      - run: git commit -am '${{ github.event.inputs.tag }}'
      - run: git -c protocol.version=2 fetch --no-tags --prune --no-recurse-submodules --depth=1 origin ${{ github.event.inputs.env }}:refs/remotes/origin/${{ github.event.inputs.env }}
      - run: git checkout --force -B ${{ github.event.inputs.env }} refs/remotes/origin/${{ github.event.inputs.env }}
      - run: git checkout -b tmp origin/master
      - run: git merge -s ours dev --squash --allow-unrelated-histories
      - run: git commit -m '${{ github.event.inputs.tag }}'
      - run: git checkout dev
      - run: git merge tmp --squash --allow-unrelated-histories
      - run: git commit -m '${{ github.event.inputs.tag }}'
      - run: git push