name: Deploy

on: 
  workflow_dispatch:
    inputs:
      tag:
        required: true
      env:
        required: true
        default: 'dev'
        options:
          - dev
          - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Builds master and commits to a deploy branch
    steps:
      - uses: actions/checkout@v2
        with:
          ref: '${{ github.event.inputs.env }}'
      - uses: denolib/setup-deno@v2
      - run: |
          git fetch --no-tags --depth=1 origin master
          git merge --no-commit --no-ff --squash master
          ./bundle
          git add .
          git commit -m "${{ github.event.inputs.tag }}"
          git push