name: Release

on: 
  workflow_dispatch:
    inputs:
      tag:
        required: true
        description: tag of release
      env:
        required: true
        default: 'dev'
        options:
          - dev
          - prod

jobs:
  release:
    runs-on: ubuntu-latest
    name: Build & commit
    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@v2
      - run: git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin ${{ github.event.inputs.env }}:refs/remotes/origin/${{ github.event.inputs.env }}
      - run: git checkout ${{ github.event.inputs.env }}
      - run: git checkout master -- *
      - run: rm public/js/.gitignore
      - run: ./bundle
      - run: git add --all
      - run: git config --global user.email "release+${{ github.actor }}@blocktol.com"
      - run: git config --global user.name "${{ github.actor }}"
      - run: git commit -am '${{ github.event.inputs.tag }}'
      - run: git push